import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import LogoutBtn from "./LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { CredentialsConfig } from "next-auth/providers/credentials";
import { OAuthConfig } from "next-auth/providers/oauth";
import "bootstrap/dist/css/bootstrap.min.css";

type UserType = {
  name: string;
  email: string;
  image: string;
};

type SessionType = {
  user: UserType;
};

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let session: SessionType | null = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          {session && session.user ? (
            <span>
              {session.user.name} <LogoutBtn />{" "}
            </span>
          ) : (
            <LoginBtn />
          )}
        </div>
        {children}
      </body>
    </html>
  );
}
